### ISSUE TITLE
Token space in .dwrc

### ISSUE THREAD

**Issue by ccoffrin** [dwavesystems/dwave-cloud-client#19]
given a `.dwrc` along these lines, note the space,
```
name|url, token
```

python3 interpreter,
```
conn = dwave_micro_client.Connection()
solver = conn.get_solver()
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dwave_micro_client.py", line 309, in get_solver
    response = self.session.get(posixpath.join(self.base_url, 'solvers/remote/{}/'.format(name)))
...
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/utils.py", line 869, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
```

**Comment by randomir** [comment]
Yup, this is a bug. Thanks for reporting!
Together with (possible bug) #18, we'll fix this soon as a part of API client auth enhancement.
