### ISSUE TITLE
ValueError not raised for Client.from_config(config_file='nonexisting')

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#55]

**Comment by randomir** [comment]
After ~#50, `ValueError` is raised only when (`endpoint`, `token`) pair is not defined after configuration loading.

That means this will fail:
```
>>> Client.from_config(config_file='nonexisting')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radomir/work/dwave-cloud-client/dwave/cloud/client.py", line 122, in from_config
    return _clients[_client](**config)
  File "/home/radomir/work/dwave-cloud-client/dwave/cloud/client.py", line 140, in __init__
    raise ValueError("Endpoint URL and/or token not defined")
ValueError: Endpoint URL and/or token not defined
```

But it'll silently pass if `endpoint` and `token` are defined with kwargs:
```
>>> Client.from_config(config_file='nonexisting', endpoint='...', token='...')
<dwave.cloud.qpu.Client object at 0x7f6dc00f5630>
```
or env vars:
```
$ DWAVE_API_ENDPOINT=x DWAVE_API_TOKEN=y python
>>> from dwave.cloud import Client
>>> Client.from_config(config_file='nonexisting')
<dwave.cloud.qpu.Client object at 0x7f8439867358>
```

This behaviour makes sense (i.e. `ValueError` == config not complete) because there are many ways of defining config file/profile (kwargs, env, autodetection, legacy file) and it's not completely clear under which circumstances should (perhaps) `IOError`/`OSError` be raised and under which we should just silence the config loading attempt and use the higher-priority values.

**Comment by randomir** [comment]
We're solving this with better error signaling, and somewhat redesigned config loading API to be more explicit about the loading process.

When user explicitly asks for a specific config file, if we fail to load the config from that file, we're raising either `dwave.cloud.exceptions.ConfigFileReadError` or `dwave.cloud.exceptions.ConfigFileParseError`.

If user opted for auto-detection of config files (`config_file=None`), we default to empty starting config in case no config files were detected. If some are detected, but unreadable, or unparseable, we raise the same exceptions as above.

Changes made as part of #93.
