### ISSUE TITLE
Missing dependency gnureadline/pyreadline for Python 2.7

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-cloud-client#80]
>>> from dwave.system.samplers import DWaveSampler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\system\samplers\__init__.py", line 1, in <module>
    from dwave.system.samplers.dwave_sampler import *
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\system\samplers\dwave_sampler.py", line 7, in <module>
    import dwave.cloud.qpu as qpuclient
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\cloud\__init__.py", line 3, in <module>
    from dwave.cloud.client import Client
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\cloud\client.py", line 16, in <module>
    from dwave.cloud.solver import Solver
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\cloud\solver.py", line 7, in <module>
    from dwave.cloud.coders import encode_bqm_as_qp
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\cloud\coders.py", line 6, in <module>
    from dwave.cloud.utils import uniform_iterator, uniform_get
  File "C:\Users\jpasvolsky\!git_Source\env\lib\site-packages\dwave\cloud\utils.py", line 4, in <module>
    import readline
**ImportError: No module named readline**

For Unix gnureadline is likely okay but if we also support Windows:

pip install gnureadline==6.3.8
Collecting gnureadline==6.3.8
  Downloading gnureadline-6.3.8.tar.gz (2.5MB)
    100% |################################| 2.5MB 483kB/s
    Complete output from command python setup.py egg_info:
    Error: this module is not meant to work on Windows (try pyreadline instead)

>pip install pyreadline
Collecting pyreadline
  Downloading pyreadline-2.1.zip (109kB)
    100% |################################| 112kB 483kB/s
Building wheels for collected packages: pyreadline
  Running setup.py bdist_wheel for pyreadline ... done
  Stored in directory: C:\Users\jpasvolsky\AppData\Local\pip\Cache\wheels\9a\c7\45\fd424eb3d7875d7a61221accd593e17c7953ed5ece5ee60be9
Successfully built pyreadline
Installing collected packages: pyreadline
Successfully installed pyreadline-2.1

Then it works:

>>> from dwave.system.samplers import DWaveSampler
>>>

**Comment by randomir** [comment]
Thanks! Fixed with #83. Also, created windows-support issue #82.
